require('../plugin/utils/getRelativePath.test.js')
require('../plugin/utils/getRawDatas.test.js')
require('../plugin/utils/getExcuteDatas.test.js')
require('../plugin/utils/getFindQuery.test.js')
require('../plugin/mongoose-relation-delete.test.js')